### ISSUE TITLE
getaddrinfo(3) requires POSIX.1-2001

### ISSUE THREAD

**Issue by gonzoleeman** [cvubrugier/target-isns#23]
The netdb library has been updated so that getaddrinfo() and friends (like gai_strerror()) are not defined in netdb.h unless one of the following is true:

  _XOPEN_SOURCE >=\ 600 || _POSIX_C_SOURCE >= 200112L

whereas it used to be:

    _POSIX_C_SOURCE >= 1 || _XOPEN_SOURCE || _POSIX_SOURCE

This means that src/isns.c needs something like the following change:

-----------------------------------------------------------------------------------------------
diff --git a/src/isns.c b/src/isns.c
index 56869c861857..43a3aa6dcc56 100644
--- a/src/isns.c
+++ b/src/isns.c
@@ -9,6 +9,7 @@
  */
 
 #define _POSIX_SOURCE
+#define _POSIX_C_SOURCE 200112L
 #include <errno.h>
 #include <inttypes.h>
 #include <limits.h>

-----------------------------------------------------------------------------------------------

I have tested this fix on openSUSE-Factory

**Comment by cvubrugier** [comment]
@gonzoleeman thank you for reporting this issue. Could you send me a pull request with the patch?
I would like you to get proper attribution for your work.

Some additional information:
* [Bug 18529 - netdb.h addrinfo namespace](https://sourceware.org/bugzilla/show_bug.cgi?id=18529)
* [Commit - netdb.h addrinfo namespace](http://repo.or.cz/w/glibc.git/commit/8737be806407be51f046b358d8824c4c968912de)

**Comment by gonzoleeman** [comment]
I sent a pull request, but I see now I should have included this additional info you have in the commit message. I would be glad to cancel and resubmit with that info added to the message, if you would like.

**Comment by cvubrugier** [comment]
> I sent a pull request, but I see now I should have included this additional info you have in the commit message. I would be glad to cancel and resubmit with that info added to the message, if you would like.

Oops, I already merged your patch. No need to resubmit your patch. Thanks again!
