### ISSUE TITLE
Oops -- missed one place where IP address is assumed little-endian

### ISSUE THREAD

**Issue by gonzoleeman** [cvubrugier/target-isns#28]
My apologies, but testing showed that my first patch only fixed one of the two places where the IP address was assumed to little-endian. I tested this time myself on s390x and x86-64, and this seems to fix it.

I will submit a pull request for the update.

**Comment by cvubrugier** [comment]
Fixed by df6f8ef334221b1e61cfd784aaf05a52d55e2485. Thanks!
