### ISSUE TITLE
Make release after fedorahosted.org retirement

### ISSUE THREAD

**Issue by cvubrugier** [cvubrugier/target-isns#33]
The fedorahosted.org server where releases of target-isns were available has been [retired](https://fedoraproject.org/wiki/Infrastructure/Fedorahosted-retirement).

As a consequence, the release tarballs of target-isns are no longer available (and I don't have them locally). I should make a new release of target-isns and upload it somewhere, probably on GitHub.

Todo:
- [ ] Update README.md to point to new location
- [ ] Make a new signed tag
- [ ] Try the release workflow of GitHub

**Comment by cvubrugier** [comment]
Fixed by tag v0.6.3.

**Comment by gonzoleeman** [comment]
Would you like this to become part of the open-iscsi project, as we've done for several other iscsi-related packages?

**Comment by cvubrugier** [comment]
> Would you like this to become part of the open-iscsi project, as we've done for several other iscsi-related packages?

You mean transferring the target-isns repository to the open-iscsi organization? I think it's a good idea.
What should I do? Just select on "Transfer ownership" under the "Settings" tabs?
